/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YtWmC0mBWKx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import { Input } from "@/components/ui/input"
import SettingsIcon from "../icons/settings"
import SendIcon from "../icons/send"
import SearchIcon from "../icons/search"
import PlusIcon from "../icons/plus"

export function Component() {
  return (
    <div className="flex h-screen w-full flex-col bg-gray-100 dark:bg-gray-900">
      <header className="flex h-16 items-center justify-between border-b bg-white px-6 dark:border-gray-800 dark:bg-gray-800">
        <div className="flex items-center gap-4">
          <Avatar className="h-8 w-8 border-2 border-gray-200 dark:border-gray-700">
            <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <h1 className="text-lg font-semibold text-gray-900 dark:text-gray-50">Chat App</h1>
        </div>
        <div className="flex items-center gap-4">
          <Button className="rounded-full" size="icon" variant="ghost">
            <SearchIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
          </Button>
          <Button className="rounded-full" size="icon" variant="ghost">
            <SettingsIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
          </Button>
        </div>
      </header>
      <div className="flex flex-1 overflow-hidden">
        <div className="border-r bg-gray-50 dark:border-gray-800 dark:bg-gray-850">
          <div className="flex h-16 items-center justify-between border-b px-6 dark:border-gray-800">
            <h2 className="text-sm font-medium text-gray-700 dark:text-gray-400">Active Users</h2>
            <Button className="rounded-full" size="icon" variant="ghost">
              <PlusIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
            </Button>
          </div>
          <div className="h-[calc(100vh-64px)] overflow-y-auto">
            <div className="space-y-4 p-4">
              <Link
                className="flex items-center gap-4 rounded-lg bg-white p-3 shadow-sm transition-colors hover:bg-gray-100 dark:bg-gray-800 dark:hover:bg-gray-750"
                href="#"
              >
                <Avatar className="h-10 w-10 border-2 border-gray-200 dark:border-gray-700">
                  <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <h3 className="text-sm font-medium text-gray-900 dark:text-gray-50">John Doe</h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Hey, how's it going?</p>
                </div>
                <div className="flex flex-col items-end">
                  <span className="text-xs text-gray-500 dark:text-gray-400">2:30 PM</span>
                  <Badge className="mt-1 bg-green-100 px-2 py-1 text-xs font-medium text-green-600 dark:bg-green-900/20 dark:text-green-400">
                    Online
                  </Badge>
                </div>
              </Link>
              <Link
                className="flex items-center gap-4 rounded-lg bg-white p-3 shadow-sm transition-colors hover:bg-gray-100 dark:bg-gray-800 dark:hover:bg-gray-750"
                href="#"
              >
                <Avatar className="h-10 w-10 border-2 border-gray-200 dark:border-gray-700">
                  <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <h3 className="text-sm font-medium text-gray-900 dark:text-gray-50">Jane Doe</h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Hey, did you see the new update?</p>
                </div>
                <div className="flex flex-col items-end">
                  <span className="text-xs text-gray-500 dark:text-gray-400">1:45 PM</span>
                  <Badge className="mt-1 bg-green-100 px-2 py-1 text-xs font-medium text-green-600 dark:bg-green-900/20 dark:text-green-400">
                    Online
                  </Badge>
                </div>
              </Link>
              <Link
                className="flex items-center gap-4 rounded-lg bg-white p-3 shadow-sm transition-colors hover:bg-gray-100 dark:bg-gray-800 dark:hover:bg-gray-750"
                href="#"
              >
                <Avatar className="h-10 w-10 border-2 border-gray-200 dark:border-gray-700">
                  <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex-1">
                  <h3 className="text-sm font-medium text-gray-900 dark:text-gray-50">Bob Smith</h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Hey, let's catch up later!</p>
                </div>
                <div className="flex flex-col items-end">
                  <span className="text-xs text-gray-500 dark:text-gray-400">12:30 PM</span>
                  <Badge className="mt-1 bg-green-100 px-2 py-1 text-xs font-medium text-green-600 dark:bg-green-900/20 dark:text-green-400">
                    Online
                  </Badge>
                </div>
              </Link>
            </div>
          </div>
        </div>
        <div className="flex flex-1 flex-col">
          <div className="h-[calc(100vh-128px)] overflow-y-auto px-6 py-4">
            <div className="space-y-4">
              <div className="flex items-start gap-4">
                <Avatar className="h-10 w-10 border-2 border-gray-200 dark:border-gray-700">
                  <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex flex-col gap-2">
                  <div className="rounded-lg bg-gray-100 p-3 text-sm text-gray-900 dark:bg-gray-800 dark:text-gray-50">
                    Hey, how's it going?
                  </div>
                  <span className="text-xs text-gray-500 dark:text-gray-400">2:30 PM</span>
                </div>
              </div>
              <div className="flex items-start gap-4 justify-end">
                <div className="flex flex-col gap-2">
                  <div className="rounded-lg bg-blue-500 p-3 text-sm text-white">
                    I'm doing great, thanks for asking!
                  </div>
                  <span className="text-xs text-gray-500 dark:text-gray-400">2:31 PM</span>
                </div>
                <Avatar className="h-10 w-10 border-2 border-gray-200 dark:border-gray-700">
                  <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
              </div>
              <div className="flex items-start gap-4">
                <Avatar className="h-10 w-10 border-2 border-gray-200 dark:border-gray-700">
                  <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="flex flex-col gap-2">
                  <div className="rounded-lg bg-gray-100 p-3 text-sm text-gray-900 dark:bg-gray-800 dark:text-gray-50">
                    That's great to hear! Did you see the new update?
                  </div>
                  <span className="text-xs text-gray-500 dark:text-gray-400">2:32 PM</span>
                </div>
              </div>
              <div className="flex items-start gap-4 justify-end">
                <div className="flex flex-col gap-2">
                  <div className="rounded-lg bg-blue-500 p-3 text-sm text-white">
                    Yes, I just checked it out. Looks really cool!
                  </div>
                  <span className="text-xs text-gray-500 dark:text-gray-400">2:33 PM</span>
                </div>
                <Avatar className="h-10 w-10 border-2 border-gray-200 dark:border-gray-700">
                  <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
              </div>
            </div>
          </div>
          <div className="border-t bg-white px-6 py-4 dark:border-gray-800 dark:bg-gray-800">
            <form className="flex items-center gap-4">
              <Input autoComplete="off" className="flex-1" id="message" placeholder="Type your message..." />
              <Button className="rounded-full" size="icon" type="submit" variant="ghost">
                <SendIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
              </Button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}






