version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    # build:
    #   context: ./docker/rabbitmq
    #   dockerfile: Dockerfile
    ports:
      - "5672:5672" # RabbitMQ broker
      - "15672:15672" # Management plugin (UI)
      - "15674:15674" # Web STOMP plugin
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_STOMP_PORT: "15674"
